### ISSUE TITLE
Build error: Invalid Regular Expression

### ISSUE THREAD

**Issue by bux** [KillahPotatoes/KP-Liberation#806]
at commit: 046e5cab13af8e50d2a483feedb38478d4aa4809

When building KP-Liberation (build.bat) I get the following error:

```log
[09:19:30] SyntaxError: Invalid regular expression: /(<Key ID="STR_MISSION_VERSION">\s*<Original>)(?<version>.+)(<\/Original>)/: Invalid group
    at stringTableReplace (C:\Users\jo\Documents\Arma 3 - Other Profiles\[SOB]%20bux\missions\_git\KP-Liberation\_tools\gulpfile.ts:76:34)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (C:\Users\jo\Documents\Arma 3 - Other Profiles\[SOB]%20bux\missions\_git\KP-Liberation\_tools\node_modules\async-done\index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by bux** [comment]
nvm, the scripts requires a higher node version
above error is on 8.4.0
switched to 12.16.2 and the build works
